name: dart_icons_generator
description: This plugin is an icons generator plugin.
version: 0.0.1
homepage: https://github.com/JosephNK/dart_icons_generator

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  build: ^2.3.0
  build_config: ^1.0.0
  recase: ^4.0.0
  dart_style: ^2.2.3
  code_builder: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.1.11

flutter:

